---
nginx_ssl: false

nginx_static_folders:
  - /var/www/static

nginx_sites:
  - server_name: example.com
    static: true
    index_title: "Example Com"
    ssl: "{{ nginx_ssl | bool }}"
    ssl_key: /etc/letsencrypt/live/example.com/privkey.pem
    ssl_crt: /etc/letsencrypt/live/example.com/fullchain.pem
  - server_name: subdomain.example.com
    static: false
    ssl: "{{ nginx_ssl | bool }}"
    ssl_key: /etc/letsencrypt/live/example.com/privkey.pem
    ssl_crt: /etc/letsencrypt/live/example.com/fullchain.pem
