---
- hosts: all
  become: true
  vars_prompt:

    - name: username
      prompt: Username of remote user?
      private: false
    #- name: userpass
    #  prompt: What is password?
    #  private: false

  tasks:
    - name: Backup files
      copy:
        src: "{{ item }}"
        remote_src: true
        dest: "{{ item }}.{{ ansible_date_time.iso8601_basic_short }}.bak"
        backup: true
        mode: 0644
      with_items:
        - /etc/ssh/sshd_config
        - /etc/sudoers
    - name: Make sudo passwordless
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'

    #- name: Enable port
    #  lineinfile:
    #    path: /etc/ssh/sshd_config
    #    state: present
    #    regexp: '^#?Port'
    #    line: 'Port 22'

    - name: Disable use PAM
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?UsePAM'
        line: 'UsePAM no'

    - name: Disable challenge response
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication no'

    - name: Enable publickey
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'

    #- name: Disable password auth
    #  lineinfile:
    #    path: /etc/ssh/sshd_config
    #    state: present
    #    regexp: '^#?PasswordAuthentication'
    #    line: 'PasswordAuthentication no'

    #- name: Disable password authentication for root
    #  lineinfile:
    #    path: /etc/ssh/sshd_config
    #    state: present
    #    regexp: '^#?PermitRootLogin'
    #    line: 'PermitRootLogin prohibit-password'

    - name: Enable public keys file
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?AuthorizedKeysFile'
        line: 'AuthorizedKeysFile  ~/.ssh/authorized_keys'

    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "*"
        update_password: on_create
        groups: sudo
        append: yes
        create_home: true

    - name: Deploy SSH Public Key
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
      #notify: restart sshd

    - name: Add some aliases
      lineinfile:
        path: /home/{{ username }}/.bashrc
        state: present
        regexp: "^{{ item }}$"
        line: "{{ item }}"
        owner: "{{ username }}"
        insertafter: EOF
        create: true
        mode: 0644
      with_items:
        - "alias ll='ls -l'"
        - "alias la='ls -A'"

  #handlers:
    #- name: restart sshd
      #shell: /usr/sbin/sshd -D