---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  #when: ansible_facts['os_family'] == 'Debian'

- name: Generate Nginx
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
    owner: root
    group: root
    mode: 0755
  with_items:
    - website.com
    - subdomain.website.com

- name: Enable Nginx
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
    owner: root
    group: root
    mode: 0755
  with_items:
    - website.com
    - subdomain.website.com

- name: Delete index.html file
  file:
    path: /var/www/html/index.html
    state: absent

- name: Generate index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0755

- name: Enable Nginx service
  service:
    name: nginx
    enabled: yes
    state: restarted
