---
- name: Create nginx folder if not exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"
    force: false
  with_items: "{{ nginx_static_folders }}"
  loop_control:
    label: "nginx static folder: {{ item }}"
