---
- name: Update apt and install required system packages
  ansible.builtin.apt:
    pkg:
      - kmod
      - ufw
    state: present
    update_cache: true

- name: UFW rules
  community.general.ufw:
    rule: "allow"
    port: "{{ item }}"
    proto: "tcp"
  with_items:
    - "22"
    - "80"
    - "443"

- name: Incoming deny
  community.general.ufw:
    state: enabled
    direction: incoming
    policy: deny
