version: '3.8'

services:
  server-1:
    container_name: ansible-ubuntu-server-1
    image: ansible-ubuntu/server:latest
    restart: unless-stopped
    networks:
      - services
  server-2:
    container_name: ansible-ubuntu-server-2
    image: ansible-ubuntu/server:latest
    restart: unless-stopped
    networks:
      - services
  server-3:
    container_name: ansible-ubuntu-server-3
    image: ansible-ubuntu/server:latest
    restart: unless-stopped
    networks:
      - services
  server-4:
    container_name: ansible-ubuntu-server-4
    image: ansible-ubuntu/server:latest
    restart: unless-stopped
    networks:
      - services

networks:
  services:
